[build]
builder = "nixpacks"
buildCommand = "prisma generate && next build"

[deploy]
startCommand = "node .next/standalone/server.js"
preDeployCommand = "prisma migrate deploy"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
